dt<-read.table("household_power_consumption.txt",stringsAsFactors = F,sep = ";",header = T)
dt<-subset(dt,dt$Date=="1/2/2007" | dt$Date=="2/2/2007")
dt$Date <- as.Date(dt$Date, format="%d/%m/%Y")
dt$Date <- as.POSIXct(paste(as.Date(dt$Date), dt$Time))
plot(dt$Sub_metering_1~dt$Date,type="l",xlab="",ylab="Energy sub metering",col="black")
lines(dt$Sub_metering_2~dt$Date,col="red")
lines(dt$Sub_metering_3~dt$Date,col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=0.5, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(device=png,"plot3.png", height=480, width=480)
dev.off()