dt<-read.table("household_power_consumption.txt",stringsAsFactors = F,sep = ";",header = T)
dt<-subset(dt,dt$Date=="1/2/2007" | dt$Date=="2/2/2007")
dt$Date <- as.Date(dt$Date, format="%d/%m/%Y")
dt$Date <- as.POSIXct(paste(as.Date(dt$Date), dt$Time))
par(mfrow=c(2,2),mar=c(4,4,2,1), oma=c(0,0,2,0))
plot(dt$Global_active_power~dt$Date,type="l",xlab="",ylab="Global Active Power")
plot(dt$Voltage~dt$Date,type="l",xlab="datetime",ylab="Voltage",col="black")
plot(dt$Sub_metering_1~dt$Date,type="l",xlab="",ylab="Energy sub metering",col="black")
lines(dt$Sub_metering_2~dt$Date,col="red")
lines(dt$Sub_metering_3~dt$Date,col="blue")
legend("topright", col=c("black", "red", "blue"),bty="n", lty=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(dt$Global_reactive_power~dt$Date,type="l",xlab="datetime",ylab="Global_reactive_power",col="black")
dev.copy(device=png,"plot4.png", height=480, width=480)
dev.off()